[data]
max_missing_samples = 4

[plot]
size = [11.0, 8.5]
font_family = 'Noto Sans'  # Set to '' to use default system font
font_scale = 1.4
grid_opacity = 0.7  # 0 is fully transparent and 1 is fully opaque
limit_zone_opacity = 0.075
limit_line_opacity = 0.7
limit_line_width = 1
date_rotation = 30

# Options: 'best', 'upper right', 'upper left', 'lower left', 'lower right',
# 'center left', 'center right', 'lower center', 'upper center', 'center'
legend_location = 'best'

[labels]
co2 = 'CO₂ (ppm)'
temp = 'Température (°C)'
humidity = 'Humidité (%)'
tvoc = 'COVT (ppb)'
tvoc_limit = 'Limite LEED, WELL et LBC'
co = 'Monoxyde de carbone (ppm x 10)'
co_limit = 'Limite anomalie légère BBI'
form = 'Formaldéhyde (ppb)'
form_limit = 'Limite anomalie légère BBI'

[axis_ranges]
co2 = [0, 2000]
temp_h = [0, 80]
tvoc = [0, 500]
co_form = [0, 50]

[limits]
humidity = [40, 60]
tvoc = 218  # ppb
co = 0.4    # ppm
form = 16   # ppb

[colors]
# See Matplotlib documentation for valid colors:
# https://matplotlib.org/stable/gallery/color/named_colors.html
co2 = 'tab:blue'
tvoc = 'tab:purple'
co = 'tab:cyan'
form = 'tab:red'
humidity = 'tab:green'
temp = 'tab:orange'
